export const socketEvents = {
  office: {
    OFFICE_CONNECTED: 'OFFICECONNECTED',
  },
  reception: {
    PASSWORD_GENERATED: 'PASSWORDGENERATED',
    RECEPTION_CONNECTED: 'RECEPTIONCONNECTED',
    PASSWORD_QUEUE_RECEPTION: 'PASSWORDQUEUERECEPTION',
    CALL_PASSWORD: 'RECEPTIONCALLPASSWORD',
    CALL_PASSWORD_NEW: 'CALL_PASSWORD_NEW',
    DISMISS_PASSWORD: 'DISMISSPASSWORD',
    PASSWORD_DISMISSED: 'PASSWORDDISMISSED',
    CONFIRM_PASSWORD: 'CONFIRMPASSWORD',
    PASSWORD_CONFIRMED: 'PASSWORDCONFIRMED',
    CLIENT_SCHEDULED: 'CLIENTSCHEDULED',
    PASSWORD_UPDATED: 'PASSWORDUPDATED',
    UPDATE_PASSWORD: 'UPDATE_PASSWORD',
  },
  panel: {
    CONNECTED: 'PANELCONNECTED',
    PASSWORD_CALLED: 'PASSWORDCALLED',
    LAST_FIVE_PASSWORDS: 'LASTFIVEPASSWORDS',
    DATA: 'PANELDATA',
    NEXT_TEN_PASSWORDS: 'NEXTTENPASSWORDS',
    MAKE_CHECKIN: 'MAKECHECKIN',
  },
  connection: {
    PANEL_REQUEST_CONNECTION: 'PANELREQUESTCONNECTION',
    TOTEM_REQUEST_CONNECTION: 'PANELREQUESTCONNECTION',
    CONNECTION_CODE_GENERATED: 'CONNECTIONCODEGENERATED',
    PANEL_CODE_AUTH_SUCCESS: 'PANELCODEAUTHSUCCESS',
  },
  command: {
    PANEL_COMMAND: 'PANELCOMMAND',
  },
  custom: {
    ERROR: 'ERROR',
  },
}
